wandb_version: 1

model:
  desc: null
  value:
    num_layers: 6
    d_model: 512
    num_heads: 8
    d_ff: 2048
    src_vocab_size: 10000
    tgt_vocab_size: 10000
    max_len: 512
    dropout: 0.1
training:
  desc: null
  value:
    epochs: 10
    batch_size: 32
    learning_rate: 0.001
    save_model: true
    model_save_path: ./models/
evaluation:
  desc: null
  value:
    batch_size: 32
    model_load_path: ./models/model_epoch_10.pt
data:
  desc: null
  value:
    data_path: ./dataset/combined_dataset.csv
    vocab:
      <pad>: 0
      <unk>: 1
      word1: 2
      word2: 3
      '...': null
    pad_token: 0
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1730499811.886764
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.9
      5: 0.15.7
      8:
      - 4
      - 5
