# Data settings
data:
  dataset_path: "dataset/combined_dataset.csv"
  source_max_len: 37
  target_max_len: 43
  pad_token: "<pad>"

# Model settings
model:
  num_layers: 6
  d_model: 512
  h: 8  # Number of heads
  d_ff: 2048
  src_vocab_size: 96038  # Vocabulary size for source
  tgt_vocab_size: 96038  # Vocabulary size for target
  max_len: 43  # Maximum sequence length (or greater if needed)
  dropout_rate: 0.1

# Training settings
training:
  batch_size: 32
  learning_rate: 0.0001
  epochs: 10
  checkpoint_dir: "checkpoints/"
